export const FETCH_SERVERS = "FETCH_SERVERS";
export const FETCH_SERVERS_START = "FETCH_SERVERS_START";
export const FETCH_SERVERS_SUCCESS = "FETCH_SERVERS_SUCCESS";
export const FETCH_SERVERS_FAIL = "FETCH_SERVERS_FAIL";

export const FETCH_SERVERS_REBOOTING = "FETCH_SERVERS_REBOOTING";
export const FETCH_SERVERS_REBOOTING_START = "FETCH_SERVERS_REBOOTING_START";
export const FETCH_SERVERS_REBOOTING_SUCCESS =
  "FETCH_SERVERS_REBOOTING_SUCCESS";
export const FETCH_SERVERS_REBOOTING_FAIL = "FETCH_SERVERS_REBOOTING_FAIL";

export const CLICK_DROPDOWN = "CLICK_DROPDOWN";
export const CLICK_DROPDOWN_START = "CLICK_DROPDOWN_START";
export const CLICK_DROPDOWN_SUCCESS = "CLICK_DROPDOWN_SUCCESS";
export const CLICK_DROPDOWN_FAIL = "CLICK_DROPDOWN_FAIL";

export const CHANGE_SEARCH = "CHANGE_SEARCH";
